POST http://localhost:5090/Breakfast HTTP/1.1
content-type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Vegan everything! Join us in a healthy breakfast full of vegan dishes and desserts",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}